export { default as Home } from './home/Home'
export { default as Layout } from './layout/Layout'
export { default as ListPage } from './listPage/ListPage'
export { default as LoginPage } from './loginPage/LoginPage'
export { default as Register } from './register/Register'
export { default as SinglePage } from './singlePage/SinglePage'
export { default as ProfilePage } from './profilePage/ProfilePage'
